### ISSUE TITLE
Issues searching for SEO keywords.

### ISSUE THREAD

**Issue by brendanteske** [david586/etsy-web-scraper-app#1] opened 2024-02-14 16:00 UTC
So first I want to say that I am by no means a programmer or know much about this stuff... More of a scriptkid type thing. But I seem to have been able to get the program running (http://localhost:3003) after doing some node install (dependencies here) as well as creating a blank exclude_words.txt file. At first I got the error about the txt file, then after creating that I get this message. Can you help me resolve this?

```
C:\etsy-seo-scraper-puppeteer-node-app>node server.js
Hi! Go to the following link in your browser to start the app: http://localhost:3003
Starting Etsy Scraping.
Search term 1: test
C:\etsy-seo-scraper-puppeteer-node-app\node_modules\@puppeteer\browsers\lib\cjs\launch.js:277
                reject(new Error([
                       ^

Error: Failed to launch the browser process! spawn ./chromium/puppeteer/chrome/win64-114.0.5735.133/chrome-win64/chrome.exe ENOENT


TROUBLESHOOTING: https://pptr.dev/troubleshooting

    at ChildProcess.onClose (C:\etsy-seo-scraper-puppeteer-node-app\node_modules\@puppeteer\browsers\lib\cjs\launch.js:277:24)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess._handle.onexit (node:internal/child_process:291:12)
    at onErrorNT (node:internal/child_process:483:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

Node.js v19.3.0
```

Thank you!

**Comment by dh-js** [comment] 2024-02-15 01:09
Hi there, the issue is that the app is expecting the chromium browser to be at path:
'./chromium/puppeteer/chrome/win64-114.0.5735.133/chrome-win64/chrome.exe'
(See lines 361 and 37 of the etsyScraperEndpoint.js file).

So this was set up to expect a 'chromium' folder in the app's root directory, which is the folder you can download from the chromium project if i remember correctly. The full path is then leading to the chrome.exe file. Alternatively to downloading chromium, if you already use Chrome for regular browsing then you can point this path to your regular (pre-existing) chrome.exe file which for Windows will be in your program files.

On lines 38 and 362 of etsyScraperEndpoint.js i would uncomment the 'headless: false' setting, and comment-out the 'headless: new' lines beneath, then the browser will be visible when it opens and you can see what is happening.

One thing to note is that Etsy have changed their bot detection and were essentially requiring you to be signed in to an Etsy account. So if you're getting captchas then there is a way you can open the browser instance with your Chrome profile, and this way as long as your Chrome profile is logged into Etsy then you shouldn't get captchas.

**Comment by brendanteske** [comment] 2024-02-16 15:56
> Hi there, the issue is that the app is expecting the chromium browser to be at path: './chromium/puppeteer/chrome/win64-114.0.5735.133/chrome-win64/chrome.exe' (See lines 361 and 37 of the etsyScraperEndpoint.js file).
> 
> So this was set up to expect a 'chromium' folder in the app's root directory, which is the folder you can download from the chromium project if i remember correctly. The full path is then leading to the chrome.exe file. Alternatively to downloading chromium, if you already use Chrome for regular browsing then you can point this path to your regular (pre-existing) chrome.exe file which for Windows will be in your program files.
> 
> On lines 38 and 362 of etsyScraperEndpoint.js i would uncomment the 'headless: false' setting, and comment-out the 'headless: new' lines beneath, then the browser will be visible when it opens and you can see what is happening.
> 
> One thing to note is that Etsy have changed their bot detection and were essentially requiring you to be signed in to an Etsy account. So if you're getting captchas then there is a way you can open the browser instance with your Chrome profile, and this way as long as your Chrome profile is logged into Etsy then you shouldn't get captchas.

Thank you for helping me on this. I got it to work by directing it to my Chrome folder (C:/Program Files (x86)/Google/Chrome/Application/chrome.exe) as you directed. After that it was throwing an error about a "created_keyword_txt_files" folder so I made that. I also edited the code to:

```
    browser = await puppeteer.launch({
//        executablePath: './chromium/puppeteer/chrome/win64-114.0.5735.133/chrome-win64/chrome.exe',
        executablePath: 'C:/Program Files (x86)/Google/Chrome/Application/chrome.exe',
		userDataDir: 'C:/chrome-dev-profile',
        //headless: false			// Browser winder is visible.
        headless: "new"		// Browser window is hidden.
    });
```

The userDataDir was my work-around for loading my logged in profile. I found this method via https://www.chromium.org/developers/creating-and-using-profiles/. I couldn't figure out what you meant about leaving an instance open because puppeteer seemed to always create a temp folder for each instance when it ran. Probably not the best way to do it? Haha...

I am now getting this error if you can help with that? Thank you in advance!

```
C:\etsy-seo-scraper-puppeteer-node-app>node server.js
Hi! Go to the following link in your browser to start the app: http://localhost:3003
Starting Etsy Scraping.
Search term 1: sticker
C:\etsy-seo-scraper-puppeteer-node-app\node_modules\puppeteer-core\lib\cjs\puppeteer\util\Deferred.js:27
                    this.reject(new Errors_js_1.TimeoutError(opts.message));
                                ^

TimeoutError: Navigation timeout of 30000 ms exceeded
    at Timeout.<anonymous> (C:\etsy-seo-scraper-puppeteer-node-app\node_modules\puppeteer-core\lib\cjs\puppeteer\util\Deferred.js:27:33)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)

Node.js v19.3.0

C:\etsy-seo-scraper-puppeteer-node-app>
```

**Comment by dh-js** [comment] 2024-02-20 05:34
No problem, glad you made progress with it. To fix the error you've mentioned above you should make the browser visible so you can see why the page wait time is timing out - it's basically saying the expected page hasn't loaded within the 30 second timeout period. But if you make the broswer visible (headless false), then when Puppeteer opens the browser, if it is not at the front of your open windows then click on it so that it is visible to you (as sometimes you need to do this for Puppeteer to run when you are using headless false), then you can see which part of the navigation isn't loading, and it may give a clue as to why

**Closed as completed** 2024-03-07 13:56 UTC
